name: build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get TAG
        id: get_tag
        run: echo TAG=${{ github.sha }} >> $GITHUB_ENV

      - name: Get Repo Owner
        id: get_repo_owner
        run: REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')

      - name: Build functions only
        run: >
          faas template store pull golang-middleware;
          OWNER="${{ env.REPO_OWNER }}"
          TAG="${{ env.TAG }}"
          faas-cli build
