name: ci/cd

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and publish
        env:
          TAG: ${{ github.sha }}
          OWNER: ${{ env.REPO_OWNER }}
        run: >
          faas template store pull golang-middleware;
          faas-cli publish
          --extra-tag ${{ env.TAG }}
          --extra-tag latest-dev
          --platforms linux/amd64,linux/arm/v7,linux/arm64

  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: build
    env:
      OPENFAAS_URL: "${{ vars.FAASD_HOST }}:${{ vars.FAASD_PORT }}"
      OPENFAAS_PASSWORD: ${{ secrets.FAASD_PASSWORD }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: connecting to tailscale network
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.52.1

      - name: testing connection
        shell: bash
        run: |
          count=10
          while ! ping -c 1 ${{ vars.FAASD_HOST }}; do
            echo "waiting..." ;
            sleep 1 ;
            let count=count-1
          done

      - name: Login
        run: |
          echo ${{secrets.FAASD_PASSWORD}} |
          faas-cli login --gateway ${{env.OPENFAAS_URL}} --password-stdin

      - name: Deploy
        env:
          TAG: ${{ github.sha }}
          OWNER: ${{ env.REPO_OWNER }}
        run: |
          faas template store pull golang-middleware;
          faas-cli deploy --gateway ${{env.OPENFAAS_URL}}
