name: 📦 deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      OPENFAAS_PREFIX: ${{ vars.DOCKER_USERNAME }}
      OPENFAAS_URL: ${{ vars.OPENFAAS_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup faas and gateway connection
        uses: ./.github/workflows/action.yml

      - name: deploy the function
        shell: bash
        env:
          REPO: ${{ github.event.repository.name }}
        run: |
          faas deploy \
            --image ${{ vars.DOCKER_USERNAME }}/$REPO:latest \
            --name $REPO
